// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa341x5TyYxaVOdaqACkyMSbEoez0iGpc',
    appId: '1:763539946053:web:4acd7c65690c6ae56ec12c',
    messagingSenderId: '763539946053',
    projectId: 'edith-454415',
    authDomain: 'edith-454415.firebaseapp.com',
    storageBucket: 'edith-454415.firebasestorage.app',
    measurementId: 'G-BZXH5P6HD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7MoY0rDJqe9itLcgMcbsKv_zuDik2BA',
    appId: '1:763539946053:android:59333a0653201da16ec12c',
    messagingSenderId: '763539946053',
    projectId: 'edith-454415',
    storageBucket: 'edith-454415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3AT-e0Lq9gz0oWn8lZVHq5j2KX9ktJ1U',
    appId: '1:763539946053:ios:f438b89d88290a0b6ec12c',
    messagingSenderId: '763539946053',
    projectId: 'edith-454415',
    storageBucket: 'edith-454415.firebasestorage.app',
    iosClientId: '763539946053-3dadhta6ppm04j1lpj227f0i3gfac1r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.edith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3AT-e0Lq9gz0oWn8lZVHq5j2KX9ktJ1U',
    appId: '1:763539946053:ios:f438b89d88290a0b6ec12c',
    messagingSenderId: '763539946053',
    projectId: 'edith-454415',
    storageBucket: 'edith-454415.firebasestorage.app',
    iosClientId: '763539946053-3dadhta6ppm04j1lpj227f0i3gfac1r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.edith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa341x5TyYxaVOdaqACkyMSbEoez0iGpc',
    appId: '1:763539946053:web:27fbf8e15cb965826ec12c',
    messagingSenderId: '763539946053',
    projectId: 'edith-454415',
    authDomain: 'edith-454415.firebaseapp.com',
    storageBucket: 'edith-454415.firebasestorage.app',
    measurementId: 'G-GPXLFLC445',
  );

}